### ISSUE TITLE
Fix caching issues

### ISSUE THREAD

**Issue by audserraCGI** [CGI-FR/IoT-Hub-Portal#65] opened 2022-01-03 13:02 UTC
Issues when updating CSS files or device model pictures, for instance.

**Comment by hocinehacherouf** [comment] 2022-06-08 19:16
Unable to reproduce this issue. Steps to reproduce it are needed.

**Comment by kbeaugrand** [comment] 2022-06-10 13:04
We close this issue for the moment.

@adcoly @Metal-Mighty , please provide us more details about your issues if you can...

**Closed by kbeaugrand** 2022-06-10 13:04 UTC
Labels: bug
